#!/bin/bash

# Dotfiles setup script - generates config files from secrets

set -e

echo "🔧 Setting up dotfiles with secrets..."

# Path to secrets file in dotfiles repo
SECRETS_FILE="$HOME/dotfiles/zsh/.zsh_secrets"

# Check if secrets file exists
if [ ! -f "$SECRETS_FILE" ]; then
    echo "❌ Error: $SECRETS_FILE not found. Please create it first."
    echo "   Copy .env.example to $SECRETS_FILE and fill in your values."
    exit 1
fi

# Source secrets
source "$SECRETS_FILE"

# Generate git/.gitconfig.local
echo "📄 Generating git/.gitconfig.local..."
cat > "$HOME/dotfiles/git/.gitconfig.local" << EOF
# Git local config — contains user identity (not committed to public repo)
# Generated by setup-secrets.sh from zsh/.zsh_secrets

[user]
	name = ${GIT_NAME}
	email = ${GIT_EMAIL}
EOF
echo "✅ Generated git/.gitconfig.local"

# Generate code/.config/github-copilot/apps.json
echo "📄 Generating code/.config/github-copilot/apps.json..."
cat > "$HOME/dotfiles/code/.config/github-copilot/apps.json" << EOF
{"github.com:${GITHUB_APP_ID}":{"user":"${GITHUB_USER}","oauth_token":"${GITHUB_COPILOT_TOKEN}","githubAppId":"${GITHUB_APP_ID}"}}
EOF
echo "✅ Generated code/.config/github-copilot/apps.json"

echo ""
echo "🎉 Setup complete! Next steps:"
echo "1. Run 'stow code git terminal tmux zsh' to link your dotfiles"
echo "2. Restart your shell or run 'source ~/.zshrc'"
echo ""
echo "🔒 Security reminder:"
echo "- Generated files contain real secrets and are gitignored"
echo "- Edit secrets in zsh/.zsh_secrets, then rerun this script"
