# Display lazygit
bind -r g display-popup -d '#{pane_current_path}' -w90% -h90% -E lazygit

# Run Opencode in a separate session
bind -r y run-shell '\
  SESSION="opencode-$(printf "%s" "#{pane_current_path}" | md5sum | cut -c1-8)"; \
  tmux -L opencode new-session -Ad -s "$SESSION" -c "#{pane_current_path}" "zsh -lic '\''op'\''"; \
  tmux -L opencode bind-key -T prefix y detach-client; \
  tmux display-popup -w90% -h90% -E "tmux -L opencode attach-session -t $SESSION"'
